name: Deployment of TryArrow in AWS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Starting the deployment
      env: # Or as an environment variable
        AWS_TRY_ARROW_PEM: ${{ secrets.AWS_TRY_ARROW_PEM }}
        AWS_EC2_IP_ADDRESS: ${{ secrets.AWS_EC2_IP_ADDRESS }}
      run: |
        printf "%s" $AWS_TRY_ARROW_PEM > ./try.arrow-kt.pem
        chmod 400 ./try.arrow-kt.pem
        ssh -o "StrictHostKeyChecking no" -q -i ./try.arrow-kt.pem $AWS_EC2_IP_ADDRESS 'ls; exit'
